on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

# Grant GITHUB_TOKEN the necessary permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build website # Replace with your project's build commands
        run: |
          npm ci
          npm run build
          
#      - name: Upload GitHub Pages artifact
#        uses: actions/upload-pages-artifact@v3
#        with:
#          name: github-pages # The artifact name must be 'github-pages' for the deploy action
#          path: dist/ # The directory containing your static files

 # deploy:
 #   environment:
 #     name: github-pages
 #     url: ${{ steps.deployment.outputs.url }}
 #   runs-on: ubuntu-latest
 #   needs: build # Ensures the build job completes first
 #   steps:
 #     - name: Deploy to GitHub Pages
 #       id: deployment
 #       uses: actions/deploy-pages@v4
